// Emit supabase/seed/seed.sql from the typed source-of-truth in apps/web/src/data/wk.ts.
//
// Usage:  pnpm seed:gen
// Output: supabase/seed/seed.sql
//
// Apply via the Supabase SQL editor after 0001_init.sql, or via
//   supabase db push   (CLI)

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  FINAL,
  GROUP_STAGE,
  QF,
  R16,
  R32,
  SF,
  TEAMS,
  THIRD_PLACE,
  VENUES,
  type KnockoutTie,
} from "../../apps/web/src/data/wk";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "seed.sql");

const esc = (s: string) => s.replaceAll("'", "''");

function toIsoUtc(date: string, kick: string): string {
  // The kickoff times in wk.ts are illustrative Brussels-local (CEST, UTC+2 in June/July).
  // We store UTC, so a `21:00 Brussels` row becomes `19:00 UTC`.
  const dt = new Date(`${date}T${kick}:00+02:00`);
  if (Number.isNaN(dt.getTime())) throw new Error(`Bad date/kick: ${date} ${kick}`);
  return dt.toISOString();
}

const teamRows = Object.values(TEAMS).map(
  (t) =>
    `('${t.code}', '${esc(t.name)}', '${t.flag}', ${t.host ?? false}, ${t.home ?? false})`,
);

const venueRows = VENUES.map(
  (v) => `('${esc(v.city)}', '${v.country}', '${esc(v.name)}', ${v.cap})`,
);

const groupMatchRows = GROUP_STAGE.map(
  (m) =>
    `(${m.n}, 'group', '${m.group}', '${toIsoUtc(m.date, m.kick)}', '${m.home}', '${m.away}', null, null)`,
);

const knockoutRows = (() => {
  const rows: string[] = [];
  const add = (t: KnockoutTie, stage: string) => {
    rows.push(
      `(${t.n}, '${stage}', null, '${toIsoUtc(t.date, t.kick)}', null, null, '${esc(t.left)}', '${esc(t.right)}')`,
    );
  };
  R32.forEach((t) => add(t, "r32"));
  R16.forEach((t) => add(t, "r16"));
  QF.forEach((t) => add(t, "qf"));
  SF.forEach((t) => add(t, "sf"));
  add(THIRD_PLACE, "third");
  add(FINAL, "final");
  return rows;
})();

const matchCount = groupMatchRows.length + knockoutRows.length;

const sql = `-- AUTO-GENERATED by supabase/seed/generate.ts — do not edit by hand.
-- Run after 0001_init.sql. Idempotent via on conflict.

-- ── teams (${Object.keys(TEAMS).length}) ──
insert into teams (code, name_nl, flag, is_host, is_home) values
${teamRows.join(",\n")}
on conflict (code) do update set
  name_nl = excluded.name_nl,
  flag    = excluded.flag,
  is_host = excluded.is_host,
  is_home = excluded.is_home;

-- ── venues (${VENUES.length}) ──
-- Re-runnable: clear and re-insert. Venues are reference data; no FK depends on the id yet.
delete from venues;
insert into venues (city, country, name, cap) values
${venueRows.join(",\n")};

-- ── matches (${matchCount}) ──
insert into matches (id, stage, group_id, kick_at, home_team, away_team, home_slot, away_slot) values
${[...groupMatchRows, ...knockoutRows].join(",\n")}
on conflict (id) do update set
  stage     = excluded.stage,
  group_id  = excluded.group_id,
  kick_at   = excluded.kick_at,
  home_team = excluded.home_team,
  away_team = excluded.away_team,
  home_slot = excluded.home_slot,
  away_slot = excluded.away_slot;
`;

writeFileSync(outPath, sql, "utf8");
console.log(`Wrote ${outPath} — ${matchCount} matches, ${teamRows.length} teams, ${venueRows.length} venues, ${sql.length} bytes.`);
